// AI-assisted: Code partially generated by Google Gemini as an adaption from staff.component.spec.ts in staff
// and adapted to fit project
import { ComponentFixture, TestBed, fakeAsync, tick } from '@angular/core/testing';
import { ReactiveFormsModule, FormsModule, FormBuilder } from '@angular/forms';
import { of } from 'rxjs';
import { BarcodeScannerComponent } from './barcode-scanner.component';
import { EquipmentService } from '../../../services/equipment.service';
import { ReservationService } from '../../../services/reservation.service';
import { BarcodeScannerService } from '../../../services/barcode-scanner.service';
import { TranslateService } from '@ngx-translate/core';
import { CustomerProfileService } from '../../../services/customer-profile.service';
import { StaffService } from '../../../services/staff.service';
import { ToastrService } from 'ngx-toastr';
import { ReservationStatus } from '../../../dtos/reservationstatus';
import { Equipment } from '../../../dtos/equipment';
import { ReservationDetail } from '../../../dtos/reservation-detail';

describe('BarcodeScannerComponent', () => {
  let component: BarcodeScannerComponent;
  let fixture: ComponentFixture<BarcodeScannerComponent>;

  let equipmentServiceSpy: jasmine.SpyObj<EquipmentService>;
  let reservationServiceSpy: jasmine.SpyObj<ReservationService>;
  let barcodeScannerServiceSpy: jasmine.SpyObj<BarcodeScannerService>;
  let translateServiceSpy: jasmine.SpyObj<TranslateService>;
  let customerProfileServiceSpy: jasmine.SpyObj<CustomerProfileService>;
  let staffServiceSpy: jasmine.SpyObj<StaffService>;
  let toastrServiceSpy: jasmine.SpyObj<ToastrService>;

  const mockEquipment1: Equipment = {
    id: 42,
    model: 'Ski Alpine Alpha',
    barcodeId: '12345678',
    equipmentType: 'SKI' as any,
    targetSkillLevel: 'ADVANCED' as any,
    price: 20.0,
    status: 'FREE' as any
  };

  const mockEquipment2: Equipment = {
    id: 43,
    model: 'Snowboard Beta',
    barcodeId: '87654321',
    equipmentType: 'SNOWBOARD' as any,
    targetSkillLevel: 'BEGINNER' as any,
    price: 15.0,
    status: 'RESERVED' as any
  };

  const mockReservation: ReservationDetail = {
    id: 101,
    customerName: 'Max Mustermann',
    startDate: '2026-06-25',
    endDate: '2026-06-27', // 3 days duration (25, 26, 27)
    reservationStatus: ReservationStatus.CREATED,
    items: [mockEquipment1]
  };

  beforeEach(async () => {
    equipmentServiceSpy = jasmine.createSpyObj('EquipmentService', ['getByBarcodeId']);
    reservationServiceSpy = jasmine.createSpyObj('ReservationService', ['search', 'addEquipmentToReservation', 'removeEquipmentFromReservation']);
    barcodeScannerServiceSpy = jasmine.createSpyObj('BarcodeScannerService', ['checkOutOrInScanWithExistingReservation', 'checkOutScanWithoutExistingReservation']);
    translateServiceSpy = jasmine.createSpyObj('TranslateService', ['instant']);
    customerProfileServiceSpy = jasmine.createSpyObj('CustomerProfileService', ['getCustomerProfilesByCustomerId']);
    staffServiceSpy = jasmine.createSpyObj('StaffService', ['searchCustomers']);
    toastrServiceSpy = jasmine.createSpyObj('ToastrService', ['success', 'error']);

    translateServiceSpy.instant.and.callFake((key: string) => key);
    staffServiceSpy.searchCustomers.and.returnValue(of([]));

    await TestBed.configureTestingModule({
      imports: [ReactiveFormsModule, FormsModule],
      declarations: [BarcodeScannerComponent],
      providers: [
        FormBuilder,
        { provide: EquipmentService, useValue: equipmentServiceSpy },
        { provide: ReservationService, useValue: reservationServiceSpy },
        { provide: BarcodeScannerService, useValue: barcodeScannerServiceSpy },
        { provide: TranslateService, useValue: translateServiceSpy },
        { provide: CustomerProfileService, useValue: customerProfileServiceSpy },
        { provide: StaffService, useValue: staffServiceSpy },
        { provide: ToastrService, useValue: toastrServiceSpy }
      ]
    }).compileComponents();

    fixture = TestBed.createComponent(BarcodeScannerComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create the component and initialize the walk-in form', () => {
    expect(component).toBeTruthy();
    expect(component.walkInForm).toBeDefined();
  });

  // --- Camera Stream Handlers ---
  describe('Camera Handlers', () => {
    it('should open and close camera stream visibility flags', () => {
      component.openCamera();
      expect(component.isCameraOpen).toBeTrue();
      component.closeCamera();
      expect(component.isCameraOpen).toBeFalse();
    });

    it('should handle onCodeResult and prevent immediate multi-scans via timeout', fakeAsync(() => {
      spyOn(component, 'searchEquipment');
      component.isScanningPaused = false;

      component.onCodeResult('987654321');

      expect(component.inputBarcodeId).toBe('987654321');
      expect(component.isScanningPaused).toBeTrue();
      expect(component.searchEquipment).toHaveBeenCalled();

      tick(1000);
      expect(component.isScanningPaused).toBeFalse();
    }));
  });

  // --- Scan Scenarios & Business Logic ---
  describe('searchEquipment & Scenario Updates', () => {
    it('should add scanned equipment and match existing reservation if found', fakeAsync(() => {
      component.inputBarcodeId = '12345678';
      equipmentServiceSpy.getByBarcodeId.and.returnValue(of(mockEquipment1));
      reservationServiceSpy.search.and.returnValue(of([mockReservation]));

      component.searchEquipment();
      tick();

      expect(component.scannedEquipments).toContain(mockEquipment1);
      expect(component.scannedEquipmentIds).toContain(mockEquipment1.id);
      expect(component.matchedReservations).toContain(mockReservation);
      expect(component.scanScenario).toBe('SINGLE_RESERVATION');
      expect(component.equipmentScenario).toBe('ALL_RESERVED_EQUIPMENT_SCANNED');
    }));

    it('should alert error if equipment is already scanned', () => {
      component.scannedEquipmentIds = [mockEquipment1.id];
      component.inputBarcodeId = '12345678';
      equipmentServiceSpy.getByBarcodeId.and.returnValue(of(mockEquipment1));

      component.searchEquipment();

      expect(toastrServiceSpy.error).toHaveBeenCalledWith('BARCODE_SCANNER.ERROR_ALREADY_SCANNED');
    });

    it('should switch to NO_RESERVATION scenario when no matching reservation is found today', fakeAsync(() => {
      component.inputBarcodeId = '12345678';
      equipmentServiceSpy.getByBarcodeId.and.returnValue(of(mockEquipment1));
      reservationServiceSpy.search.and.returnValue(of([]));

      component.searchEquipment();
      tick();

      expect(component.scanScenario).toBe('NO_RESERVATION');
    }));
  });

  // --- Session Modification & Reservation Sync ---
  describe('Equipment Modification in Current Session', () => {
    it('should clear equipment from active scan session list locally upon removeEquipmentFromList', () => {
      component.scannedEquipments = [mockEquipment1];
      component.scannedEquipmentIds = [mockEquipment1.id];
      component.matchedReservations = [mockReservation];

      component.removeEquipmentFromList(mockEquipment1);

      expect(component.scannedEquipments.length).toBe(0);
      expect(component.scannedEquipmentIds.length).toBe(0);
    });

    it('should invoke reservationService.removeEquipmentFromReservation when removing item directly from backend reservation', () => {
      component.matchedReservations = [mockReservation];
      component.scanScenario = 'SINGLE_RESERVATION';
      reservationServiceSpy.removeEquipmentFromReservation.and.returnValue(of({ ...mockReservation, items: [] }));

      component.removeEquipmentFromExistingReservation(mockEquipment1.id);

      expect(reservationServiceSpy.removeEquipmentFromReservation).toHaveBeenCalledWith({
        id: mockReservation.id,
        equipmentIds: [mockEquipment1.id]
      });
    });

    it('should invoke reservationService.addEquipmentToReservation when appending unreserved scanned equipment', () => {
      component.matchedReservations = [mockReservation];
      reservationServiceSpy.addEquipmentToReservation.and.returnValue(of(mockReservation));

      component.addEquipmentToExistingReservation(mockEquipment1.id);

      expect(reservationServiceSpy.addEquipmentToReservation).toHaveBeenCalledWith({
        id: mockReservation.id,
        equipmentIds: [mockEquipment1.id]
      });
    });
  });

  // --- Dynamic Pricing & Visual Helpers ---
  describe('scannedItemsTotalPrice Calculation', () => {
    it('should return 0 if no equipment is scanned', () => {
      component.scannedEquipments = [];
      expect(component.scannedItemsTotalPrice).toBe(0);
    });

    it('should calculate price based on walk-in form runtime if scanScenario is NO_RESERVATION', () => {
      component.scanScenario = 'NO_RESERVATION';
      component.scannedEquipments = [mockEquipment1, mockEquipment2]; // Total 35.0 per day

      component.walkInForm.patchValue({
        startDate: '2026-06-01',
        endDate: '2026-06-04' // 4 days runtime
      });

      expect(component.scannedItemsTotalPrice).toBe(140);
    });

    it('should calculate price based on reservation runtime if matchedReservations has exactly 1 entry', () => {
      component.scanScenario = 'SINGLE_RESERVATION';
      component.matchedReservations = [mockReservation]; // 3 days runtime
      component.scannedEquipments = [mockEquipment1]; // 20.0 per day

      expect(component.scannedItemsTotalPrice).toBe(60);
    });

    it('should fallback to 1 day runtime if scanScenario is single/conflict but criteria list bounds are unmatched', () => {
      component.scanScenario = 'CONFLICT_RESERVATION';
      component.matchedReservations = [];
      component.scannedEquipments = [mockEquipment1];

      expect(component.scannedItemsTotalPrice).toBe(20);
    });
  });

  describe('getStatusClass Style Mapper', () => {
    it('should map FREE to bg-success', () => {
      expect(component.getStatusClass('FREE')).toBe('bg-success');
    });

    it('should map RESERVED to bg-warning text-dark', () => {
      expect(component.getStatusClass('RESERVED')).toBe('bg-warning text-dark');
    });

    it('should map RENTED to bg-danger', () => {
      expect(component.getStatusClass('RENTED')).toBe('bg-danger');
    });

    it('should map MAINTENANCE to bg-secondary', () => {
      expect(component.getStatusClass('MAINTENANCE')).toBe('bg-secondary');
    });

    it('should fallback to bg-light text-dark on unknown status values', () => {
      expect(component.getStatusClass('UNKNOWN_STATUS')).toBe('bg-light text-dark');
    });
  });

  // --- Submission Orchestration ---
  describe('Reservation Submissions', () => {
    it('should submit existing reservation updates when scenario criteria are satisfied', () => {
      component.matchedReservations = [{ ...mockReservation, reservationStatus: ReservationStatus.CREATED }];
      component.scanScenario = 'SINGLE_RESERVATION';
      component.equipmentScenario = 'ALL_RESERVED_EQUIPMENT_SCANNED';
      component.scannedEquipmentIds = [mockEquipment1.id];

      barcodeScannerServiceSpy.checkOutOrInScanWithExistingReservation.and.returnValue(of({} as any));

      component.submitExistingReservation();

      expect(barcodeScannerServiceSpy.checkOutOrInScanWithExistingReservation).toHaveBeenCalledWith({
        id: mockReservation.id,
        reservationStatus: ReservationStatus.PICKED_UP,
        equipmentIds: [mockEquipment1.id]
      });
    });

    it('should block walk-in form submission if end-date range check fails', () => {
      component.walkInForm.patchValue({ endDate: '2020-01-01' });
      spyOn(component, 'submitWalkInCheckout').and.callThrough();

      expect(component.isWalkInDateRangeInvalid).toBeTrue();
    });
  });
});
