// AI-assisted: Code partially generated by Google Gemini as an adaption from staff.component.spec.ts in staff
// and adapted to fit project
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { Router } from '@angular/router';
import { TranslateModule } from '@ngx-translate/core';
import { provideHttpClient } from '@angular/common/http';
import { provideHttpClientTesting } from '@angular/common/http/testing';
import { By } from '@angular/platform-browser';
import { CustomerComponent } from './customer.component';
import { RouterTestingModule } from '@angular/router/testing';

describe('CustomerComponent', () => {
  let component: CustomerComponent;
  let fixture: ComponentFixture<CustomerComponent>;
  let router: Router;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [CustomerComponent],
      imports: [
        RouterTestingModule.withRoutes([
          { path: 'customer', component: CustomerComponent },
          { path: 'customer/inventory', component: CustomerComponent }
        ]),
        TranslateModule.forRoot()
      ],
      providers: [
        provideHttpClient(),
        provideHttpClientTesting()
      ]
    }).compileComponents();

    fixture = TestBed.createComponent(CustomerComponent);
    component = fixture.componentInstance;
    router = TestBed.inject(Router);
  });

  async function navigateTo(url: string) {
    await router.navigateByUrl(url);
    fixture.detectChanges();
  }

  it('should create', async () => {
    await navigateTo('/customer');
    expect(component).toBeTruthy();
  });

  describe('isChildRouteActive', () => {
    it('should return false when the current URL is exactly "/customer"', async () => {
      await navigateTo('/customer');

      expect(component.isChildRouteActive()).toBeFalse();
    });

    it('should return false when the current URL is exactly "/customer/"', async () => {
      await navigateTo('/customer');

      spyOnProperty(router, 'url', 'get').and.returnValue('/customer/');
      expect(component.isChildRouteActive()).toBeFalse();
    });

    it('should return true when a child route is active (e.g., "/customer/inventory")', async () => {
      await navigateTo('/customer/inventory');

      expect(component.isChildRouteActive()).toBeTrue();
    });
  });

  describe('Template Rendering', () => {
    it('should display the dashboard grid when no child route is active', async () => {
      await navigateTo('/customer');

      const dashboardElement = fixture.debugElement.query(By.css('.customer-dashboard'));
      const routerOutletElement = fixture.debugElement.query(By.css('router-outlet'));

      expect(dashboardElement).toBeTruthy();
      expect(routerOutletElement).toBeTruthy();
    });

    it('should hide the dashboard grid when a child route is active', async () => {
      await navigateTo('/customer/inventory');

      const dashboardElement = fixture.debugElement.query(By.css('.customer-dashboard'));
      const routerOutletElement = fixture.debugElement.query(By.css('router-outlet'));

      expect(dashboardElement).toBeNull();
      expect(routerOutletElement).toBeTruthy();
    });
  });
});
