//AI-assisted: Code generated by Google Gemini and adapted to fit project
import { ComponentFixture, TestBed, waitForAsync } from '@angular/core/testing';
import { HeaderComponent } from './header.component';
import { AppComponent } from "../../app.component";
import { AuthService } from '../../services/auth.service';
import { TranslateModule, TranslateService } from '@ngx-translate/core';
import { RouterTestingModule } from '@angular/router/testing';

describe('HeaderComponent', () => {
  let component: HeaderComponent;
  let fixture: ComponentFixture<HeaderComponent>;
  let translateService: TranslateService;

  let authServiceMock: jasmine.SpyObj<AuthService>;
  let appComponentMock: any;

  beforeEach(waitForAsync(() => {
    authServiceMock = jasmine.createSpyObj('AuthService', ['isLoggedIn', 'logoutUser', 'getUserEmail']);
    authServiceMock.isLoggedIn.and.returnValue(false);
    authServiceMock.getUserEmail.and.returnValue('test@user.com');

    appComponentMock = {
      title: 'SRIMS',
      switchLanguage: jasmine.createSpy('switchLanguage')
    };

    TestBed.configureTestingModule({
      declarations: [HeaderComponent],
      imports: [
        RouterTestingModule,
        TranslateModule.forRoot()
      ],
      providers: [
        { provide: AuthService, useValue: authServiceMock },
        { provide: AppComponent, useValue: appComponentMock }
      ]
    }).compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(HeaderComponent);
    component = fixture.componentInstance;
    translateService = TestBed.inject(TranslateService);
  });

  it('should create', () => {
    fixture.detectChanges(); // Manuell triggern, da es im beforeEach fehlt
    expect(component).toBeTruthy();
  });

  it('should return isLoggedIn false when user is not logged in', () => {
    authServiceMock.isLoggedIn.and.returnValue(false);
    fixture.detectChanges();

    expect(component.authService.isLoggedIn()).toBeFalse();
  });

  it('should return isLoggedIn true when user is logged in', () => {
    authServiceMock.isLoggedIn.and.returnValue(true);
    fixture.detectChanges();

    expect(component.authService.isLoggedIn()).toBeTrue();
  });

  it('should call logoutUser on authService when logout link is clicked', () => {
    authServiceMock.isLoggedIn.and.returnValue(true);

    fixture.detectChanges();

    component.authService.logoutUser();
    expect(authServiceMock.logoutUser).toHaveBeenCalled();
  });

  it('should correctly identify if the current language is English', () => {
    fixture.detectChanges();
    translateService.use('en');
    expect(component.isEnglish).toBeTrue();

    translateService.use('de');
    expect(component.isEnglish).toBeFalse();
  });

  it('should switch language to English when current language is German', () => {
    fixture.detectChanges();
    translateService.use('de');

    component.toggleLanguage();
    expect(appComponentMock.switchLanguage).toHaveBeenCalledWith('en');
  });

  it('should switch language to German when current language is English', () => {
    fixture.detectChanges();
    translateService.use('en');

    component.toggleLanguage();
    expect(appComponentMock.switchLanguage).toHaveBeenCalledWith('de');
  });
});
