// AI-assisted: Code partially generated by Google Gemini and adapted to fit project
import { ComponentFixture, TestBed, waitForAsync } from '@angular/core/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { CustomerEquipmentViewComponent } from './equipment-view.component';
import { EquipmentService } from '../../../../services/equipment.service';
import { provideHttpClientTesting } from '@angular/common/http/testing';
import { provideHttpClient, withInterceptorsFromDi } from '@angular/common/http';
import { TranslateModule } from '@ngx-translate/core';
import { ActivatedRoute } from '@angular/router';
import { of } from 'rxjs';
import { registerLocaleData } from '@angular/common';
import localeDe from '@angular/common/locales/de';

registerLocaleData(localeDe, 'de');

describe('CustomerEquipmentViewComponent', () => {
  let component: CustomerEquipmentViewComponent;
  let fixture: ComponentFixture<CustomerEquipmentViewComponent>;
  let equipmentServiceSpy: jasmine.SpyObj<EquipmentService>;

  beforeEach(waitForAsync(() => {
    const eqSpy = jasmine.createSpyObj('EquipmentService', ['getById']);

    TestBed.configureTestingModule({
      declarations: [CustomerEquipmentViewComponent],
      imports: [
        RouterTestingModule,
        TranslateModule.forRoot()
      ],
      providers: [
        provideHttpClient(withInterceptorsFromDi()),
        provideHttpClientTesting(),
        { provide: EquipmentService, useValue: eqSpy },
        {
          provide: ActivatedRoute,
          useValue: {
            snapshot: {
              paramMap: {
                get: () => '1'
              }
            }
          }
        }
      ]
    }).compileComponents();

    equipmentServiceSpy = TestBed.inject(EquipmentService) as jasmine.SpyObj<EquipmentService>;
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(CustomerEquipmentViewComponent);
    component = fixture.componentInstance;

    equipmentServiceSpy.getById.and.returnValue(of({
      id: 1,
      barcodeId: '12345',
      price: 25.0,
      model: 'Test Ski',
      status: 'FREE',
      targetSkillLevel: 'BEGINNER',
      equipmentType: 'SKI',
      length: 170
    } as any));

    fixture.detectChanges();
  });

  it('should create the view component', () => {
    expect(component).toBeTruthy();
  });

  it('should load equipment successfully on init', () => {
    expect(component.equipment).toBeTruthy();
    expect(component.equipment?.id).toBe(1);
    expect(component.equipment?.model).toBe('Test Ski');
    expect(component.loading).toBeFalse();
    expect(component.error).toBeFalse();
    expect(equipmentServiceSpy.getById).toHaveBeenCalledWith(1);
  });
});
