import {Component} from '@angular/core';
import {EquipmentCreation} from "../../../../dtos/equipment-creation";
import {EquipmentType} from "../../../../dtos/equipmenttype";
import {RentalStatus} from "../../../../dtos/rentalstatus";
import {SkillLevel} from "../../../../dtos/skilllevel";
import {EquipmentService} from "../../../../services/equipment.service";
import {Router} from "@angular/router";

//AI-assisted: Code generated by ChatGPT and adapted
@Component({
  selector: 'app-equipment-create',
  templateUrl: './equipment-create.component.html',
  styleUrl: './equipment-create.component.scss',
  standalone: false
})
export class EquipmentCreateComponent {

  equipment: EquipmentCreation = {
    type: EquipmentType.SKI,
    model: '',
    status: RentalStatus.FREE,
    targetSkillLevel: SkillLevel.BEGINNER,
    price: 0,
    length: undefined,
    size: undefined,
    soleLengthMm: undefined,
    lancingSystem: ''
  };

  equipmentTypes = [
    EquipmentType.HELMET,
    EquipmentType.SKI,
    EquipmentType.POLE,
    EquipmentType.SKIBOOT,
    EquipmentType.SNOWBOARD,
    EquipmentType.SNOWBOARDBOOT,
  ]

  rentalStatuses = [
    RentalStatus.FREE,
    RentalStatus.RESERVED,
    RentalStatus.RENTED,
    RentalStatus.MAINTENANCE
  ]

  skillLevels = [
    SkillLevel.BEGINNER,
    SkillLevel.INTERMEDIATE,
    SkillLevel.ADVANCED
  ]


  loading = false;
  error = false;

  constructor(private equipmentService: EquipmentService, private router: Router) {
  }

  createEquipment(): void {
    this.loading = true;
    this.error = false;

    this.equipmentService.create(this.buildCreateRequest()).subscribe({
      next: () => {
        this.loading = false;
        this.router.navigate(['/staff/inventory']);
      },
      error: err => {
        console.error('Failed to create equipment', err);
        this.error = true;
        this.loading = false;
      }
    });
  }


  onTypeChange(): void {
    this.equipment.length = undefined;
    this.equipment.size = undefined;
    this.equipment.soleLengthMm = undefined;
    this.equipment.lancingSystem = '';
  }

  cancel(): void {
    this.router.navigate(['/staff/inventory']);
  }

  private buildCreateRequest(): EquipmentCreation {
    const request: EquipmentCreation = {
      type: this.equipment.type,
      model: this.equipment.model,
      status: this.equipment.status,
      targetSkillLevel: this.equipment.targetSkillLevel,
      price: this.equipment.price,
    };

    if (this.equipment.type === EquipmentType.SKI || this.equipment.type === EquipmentType.POLE || this.equipment.type === EquipmentType.SNOWBOARD){
      request.length =  this.equipment.length;
    }

    if (this.equipment.type === EquipmentType.HELMET) {
      request.size = this.equipment.size;
    }

    if (this.equipment.type === EquipmentType.SKIBOOT) {
      request.soleLengthMm = this.equipment.soleLengthMm;
    }

    if (this.equipment.type === EquipmentType.SNOWBOARDBOOT) {
      request.lancingSystem = this.equipment.lancingSystem;
    }

    return request;
  }

  getMinLength(): number {
    switch (this.equipment.type) {
      case EquipmentType.SKI:
      case EquipmentType.POLE:
        return 70;
      case EquipmentType.SNOWBOARD:
        return 80;
      default:
        return 0;
    }
  }

  getMaxLength(): number {
    switch (this.equipment.type) {
      case EquipmentType.SKI:
        return 210;
      case EquipmentType.POLE:
        return 145;
      case EquipmentType.SNOWBOARD:
        return 180;
      default:
        return 999;
    }
  }
}
