import {ComponentFixture, TestBed} from '@angular/core/testing';
import {FormsModule} from "@angular/forms";
import {TranslateModule} from "@ngx-translate/core";
import {of, throwError} from "rxjs";
import {ActivatedRoute, convertToParamMap, Router} from "@angular/router";

import {EquipmentCreateEditComponent, EquipmentCreateEditMode} from "./equipment-create-edit.component";
import {EquipmentService} from "../../../../services/equipment.service";
import {RentalStatus} from "../../../../dtos/rentalstatus";
import {EquipmentType} from "../../../../dtos/equipmenttype";
import {SkillLevel} from "../../../../dtos/skilllevel";

//AI-assisted: Code generated by ChatGPT and adapted
describe('EquipmentCreateEditComponent', () => {
  let component: EquipmentCreateEditComponent;
  let fixture: ComponentFixture<EquipmentCreateEditComponent>;
  let equipmentServiceMock: jasmine.SpyObj<EquipmentService>;

  const routerMock = {
    navigate: jasmine.createSpy("navigate"),
  };

  const activatedRouteMock = {
    snapshot: {
      paramMap: convertToParamMap({})
    }
  };

  beforeEach(async () => {
    equipmentServiceMock = jasmine.createSpyObj('EquipmentService', ['create', 'update', 'getById']);
    equipmentServiceMock.create.and.returnValue(of({} as any));
    equipmentServiceMock.update.and.returnValue(of({} as any));
    equipmentServiceMock.getById.and.returnValue(of({
      id: 1,
      barcodeId: 'BC-1',
      price: 20,
      model: 'Loaded Model',
      status: RentalStatus.FREE,
      targetSkillLevel: SkillLevel.BEGINNER,
      equipmentType: EquipmentType.SKI,
      length: 160
    }));

    activatedRouteMock.snapshot.paramMap = convertToParamMap({});
    routerMock.navigate.calls.reset();

    await TestBed.configureTestingModule({
      declarations: [EquipmentCreateEditComponent],
      imports: [FormsModule, TranslateModule.forRoot()],
      providers: [
        { provide: EquipmentService, useValue: equipmentServiceMock },
        { provide: Router, useValue: routerMock },
        { provide: ActivatedRoute, useValue: activatedRouteMock }
      ]
    })
    .compileComponents();

    fixture = TestBed.createComponent(EquipmentCreateEditComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
    await fixture.whenStable();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('should call create service and navigate back to inventory', () => {
    component.equipment = {
      type: EquipmentType.SKI,
      model: 'Test Ski',
      status: RentalStatus.FREE,
      targetSkillLevel: SkillLevel.BEGINNER,
      price: 20,
      length: 160
    };

    component.onSubmit();

    expect(equipmentServiceMock.create).toHaveBeenCalledWith({
      type: EquipmentType.SKI,
      model: 'Test Ski',
      status: RentalStatus.FREE,
      targetSkillLevel: SkillLevel.BEGINNER,
      price: 20,
      length: 160
    });
    expect(routerMock.navigate).toHaveBeenCalledWith(['/staff/inventory']);
    expect(component.loading).toBeFalse();
    expect(component.error).toBeFalse();
  });

  it('should set error when create request fails', () => {
    equipmentServiceMock.create.and.returnValue(throwError(() => new Error('Create failed')));

    component.onSubmit();

    expect(component.error).toBeTrue();
    expect(component.loading).toBeFalse();
    expect(routerMock.navigate).not.toHaveBeenCalled();
  });

  it('should switch to edit mode and load equipment when id route param exists', () => {
    activatedRouteMock.snapshot.paramMap = convertToParamMap({ id: '42' });

    component.ngOnInit();

    expect(component.mode).toBe(EquipmentCreateEditMode.edit);
    expect(component.equipmentId).toBe(42);
    expect(equipmentServiceMock.getById).toHaveBeenCalledWith(42);
    expect(component.equipment.model).toBe('Loaded Model');
  });

  it('should call update service and navigate back to inventory in edit mode', () => {
    component.mode = EquipmentCreateEditMode.edit;
    component.equipmentId = 123;
    component.equipment = {
      type: EquipmentType.HELMET,
      model: 'Helmet X',
      status: RentalStatus.FREE,
      targetSkillLevel: SkillLevel.INTERMEDIATE,
      price: 35,
      size: 58
    };

    component.onSubmit();

    expect(equipmentServiceMock.update).toHaveBeenCalledWith(123, {
      type: EquipmentType.HELMET,
      model: 'Helmet X',
      status: RentalStatus.FREE,
      targetSkillLevel: SkillLevel.INTERMEDIATE,
      price: 35,
      length: null,
      size: 58,
      soleLengthMm: null,
      lancingSystem: null
    });
    expect(routerMock.navigate).toHaveBeenCalledWith(['/staff/inventory']);
    expect(component.loading).toBeFalse();
    expect(component.error).toBeFalse();
  });

  it('should set error when update request fails', () => {
    component.mode = EquipmentCreateEditMode.edit;
    component.equipmentId = 10;
    equipmentServiceMock.update.and.returnValue(throwError(() => new Error('Update failed')));

    component.onSubmit();

    expect(component.error).toBeTrue();
    expect(component.loading).toBeFalse();
    expect(routerMock.navigate).not.toHaveBeenCalled();
  });
});
