import {Component, OnInit} from '@angular/core';
import {EquipmentCreation} from "../../../../dtos/equipment-creation";
import {EquipmentUpdate} from "../../../../dtos/equipment-update";
import {EquipmentType} from "../../../../dtos/equipmenttype";
import {RentalStatus} from "../../../../dtos/rentalstatus";
import {SkillLevel} from "../../../../dtos/skilllevel";
import {EquipmentService} from "../../../../services/equipment.service";
import {ActivatedRoute, Router} from "@angular/router";

export enum EquipmentCreateEditMode {
  create,
  edit
};

//AI-assisted: Code generated by ChatGPT and adapted
@Component({
  selector: 'app-equipment-create',
  templateUrl: './equipment-create-edit.component.html',
  styleUrl: './equipment-create-edit.component.scss',
  standalone: false
})
export class EquipmentCreateEditComponent implements OnInit {
  readonly EquipmentCreateEditMode = EquipmentCreateEditMode;

  mode: EquipmentCreateEditMode = EquipmentCreateEditMode.create;
  equipmentId?: number;
  equipment: EquipmentCreation = {
    type: EquipmentType.SKI,
    model: '',
    status: RentalStatus.FREE,
    targetSkillLevel: SkillLevel.BEGINNER,
    price: 0,
    creationNumber: 1,
    length: undefined,
    size: undefined,
    soleLengthMm: undefined,
    lacingSystem: ''
  };

  equipmentTypes = [
    EquipmentType.HELMET,
    EquipmentType.SKI,
    EquipmentType.POLE,
    EquipmentType.SKIBOOT,
    EquipmentType.SNOWBOARD,
    EquipmentType.SNOWBOARDBOOT,
  ]

  rentalStatuses = [
    RentalStatus.FREE,
    RentalStatus.RESERVED,
    RentalStatus.RENTED,
    RentalStatus.MAINTENANCE
  ]

  skillLevels = [
    SkillLevel.BEGINNER,
    SkillLevel.INTERMEDIATE,
    SkillLevel.ADVANCED
  ]


  loading = false;
  error = false;

  constructor(private equipmentService: EquipmentService, private router: Router, private route: ActivatedRoute) {
  }

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');

    if (id) {
      this.mode = EquipmentCreateEditMode.edit;
      this.equipmentId = Number(id);
      this.loadEquipment(this.equipmentId);
    }
  }

  private loadEquipment(id: number): void {
    this.loading = true;
    this.equipmentService.getById(id).subscribe({
      next: (data) => {
        this.equipment = {
          type: data.equipmentType,
          model: data.model,
          status: data.status,
          targetSkillLevel: data.targetSkillLevel,
          price: data.price,
          creationNumber: 1,

          length: data.length,
          size: data.size,
          soleLengthMm: data.soleLengthMm,
          lacingSystem: data.lacingSystem
        };

        this.loading = false;
      },
      error: (err) => {
        console.error('Failed to load equipment', err);
        this.error = true;
        this.loading = false;
      }
    });
  }

  onSubmit(): void {
    this.loading = true;
    this.error = false;

    if (this.mode === EquipmentCreateEditMode.create) {
      const request: EquipmentCreation = this.buildCreateRequest();

      this.equipmentService.create(request).subscribe({
        next: () => {
          this.loading = false;
          this.router.navigate(['/staff/inventory']);
        },
        error: err => {
          console.error('Failed to create equipment', err);
          this.error = true;
          this.loading = false;
        }
      });
    } else {
      const request: EquipmentUpdate = this.buildUpdateRequest();

      this.equipmentService.update(this.equipmentId!, request).subscribe({
        next: () => {
          this.loading = false;
          this.router.navigate(['/staff/inventory']);
        },
        error: err => {
          console.error('Failed to update equipment', err);
          this.error = true;
          this.loading = false;
        }
      });
    }
  }

  //TODO maybe remove onTypeChange depending on how we want create and edit to work, or maybe just remove for editing
  onTypeChange(): void {
    this.equipment.length = undefined;
    this.equipment.size = undefined;
    this.equipment.soleLengthMm = undefined;
    this.equipment.lacingSystem = '';
  }

  cancel(): void {
    this.router.navigate(['/staff/inventory']);
  }

  private buildCreateRequest(): EquipmentCreation {
    const request: EquipmentCreation = {
      type: this.equipment.type,
      model: this.equipment.model,
      status: this.equipment.status,
      targetSkillLevel: this.equipment.targetSkillLevel,
      price: this.equipment.price,
      creationNumber: this.equipment.creationNumber,
    };

    if (this.equipment.type === EquipmentType.SKI || this.equipment.type === EquipmentType.POLE || this.equipment.type === EquipmentType.SNOWBOARD) {
      request.length = this.equipment.length;
    }

    if (this.equipment.type === EquipmentType.HELMET) {
      request.size = this.equipment.size;
    }

    if (this.equipment.type === EquipmentType.SKIBOOT) {
      request.soleLengthMm = this.equipment.soleLengthMm;
    }

    if (this.equipment.type === EquipmentType.SNOWBOARDBOOT) {
      request.lacingSystem = this.equipment.lacingSystem;
    }

    return request;
  }

  private buildUpdateRequest(): EquipmentUpdate {
    return {
      type: this.equipment.type,
      model: this.equipment.model,
      status: this.equipment.status,
      targetSkillLevel: this.equipment.targetSkillLevel,
      price: this.equipment.price,

      length:
        this.equipment.type === EquipmentType.SKI ||
        this.equipment.type === EquipmentType.POLE ||
        this.equipment.type === EquipmentType.SNOWBOARD
          ? (this.equipment.length ?? null)
          : null,

      size:
        this.equipment.type === EquipmentType.HELMET
          ? (this.equipment.size ?? null)
          : null,

      soleLengthMm:
        this.equipment.type === EquipmentType.SKIBOOT
          ? (this.equipment.soleLengthMm ?? null)
          : null,

      lacingSystem:
        this.equipment.type === EquipmentType.SNOWBOARDBOOT
          ? (this.equipment.lacingSystem?.trim() || null)
          : null
    }
  }

  getMinLength(): number {
    switch (this.equipment.type) {
      case EquipmentType.SKI:
      case EquipmentType.POLE:
        return 70;
      case EquipmentType.SNOWBOARD:
        return 80;
      default:
        return 0;
    }
  }

  getMaxLength(): number {
    switch (this.equipment.type) {
      case EquipmentType.SKI:
        return 210;
      case EquipmentType.POLE:
        return 145;
      case EquipmentType.SNOWBOARD:
        return 180;
      default:
        return 999;
    }
  }
}
