// AI-assisted: Code generated by Google Gemini and adapted to fit project
import {ComponentFixture, fakeAsync, TestBed, tick} from '@angular/core/testing';
import {FormBuilder, FormsModule, ReactiveFormsModule} from '@angular/forms';
import {ActivatedRoute, convertToParamMap, Router} from '@angular/router';
import {of} from 'rxjs';
import {ReservationCreateEditComponent, ReservationCreateEditMode} from './reservation-create-edit.component';
import {ReservationService} from '../../../../services/reservation.service';
import {EquipmentService} from '../../../../services/equipment.service';
import {CustomerProfileService} from '../../../../services/customer-profile.service';
import {EquipmentType} from '../../../../dtos/equipmenttype';
import {RentalStatus} from '../../../../dtos/rentalstatus';
import {SkillLevel} from '../../../../dtos/skilllevel';
import {TranslateModule, TranslateService} from '@ngx-translate/core';
import {ToastrModule, ToastrService} from 'ngx-toastr';
import {NgbModule} from '@ng-bootstrap/ng-bootstrap';

describe('ReservationCreateEditComponent', () => {
  let component: ReservationCreateEditComponent;
  let fixture: ComponentFixture<ReservationCreateEditComponent>;

  let reservationServiceMock: any;
  let equipmentServiceMock: any;
  let customerProfileServiceMock: any;
  let routerMock: any;
  let activatedRouteMock: any;
  let toastrServiceMock: jasmine.SpyObj<ToastrService>;
  let mockDialog: jasmine.SpyObj<HTMLDialogElement>;

  const mockProfiles = [
    {
      id: 1,
      profileName: 'Test Profil 1',
      skillLevel: SkillLevel.BEGINNER,
      customerId: 1,
      height: 180,
      shoeSize: 42,
      weight: 75
    }
  ];

  const mockEquipment = [
    {
      id: 10,
      model: 'Ski Alpha',
      price: 25,
      equipmentType: EquipmentType.SKI,
      status: RentalStatus.FREE,
      targetSkillLevel: SkillLevel.BEGINNER,
      barcodeId: 'BC-12345'
    },
    {
      id: 20,
      model: 'Ski Beta',
      price: 35,
      equipmentType: EquipmentType.SKI,
      status: RentalStatus.FREE,
      targetSkillLevel: SkillLevel.ADVANCED,
      barcodeId: 'BC-54321'
    }
  ];

  beforeEach(async () => {
    reservationServiceMock = {
      create: jasmine.createSpy('create').and.returnValue(of({id: 99})),
      update: jasmine.createSpy('update').and.returnValue(of({id: 100})),
      getById: jasmine.createSpy('getById').and.returnValue(of({
        id: 100,
        customerProfileId: 1,
        pickUpTime: '10:00',
        startDate: '2026-06-20',
        endDate: '2026-06-22',
        items: [mockEquipment[0]]
      }))
    };

    equipmentServiceMock = {
      search: jasmine.createSpy('search').and.returnValue(of(mockEquipment))
    };

    customerProfileServiceMock = {
      getCustomerProfiles: jasmine.createSpy('getCustomerProfiles').and.returnValue(of(mockProfiles))
    };

    routerMock = {
      navigate: jasmine.createSpy('navigate')
    };

    activatedRouteMock = {
      snapshot: {
        data: {mode: ReservationCreateEditMode.create},
        paramMap: convertToParamMap({})
      }
    };
    toastrServiceMock = jasmine.createSpyObj('ToastrService', ['success', 'error', 'warning', 'info']);

    mockDialog = jasmine.createSpyObj('HTMLDialogElement', ['close', 'showModal']);

    await TestBed.configureTestingModule({
      declarations: [
        ReservationCreateEditComponent,
      ],
      imports: [
        ReactiveFormsModule,
        FormsModule,
        NgbModule,
        TranslateModule.forRoot(),
        ToastrModule.forRoot()
      ],
      providers: [
        FormBuilder,
        {provide: ReservationService, useValue: reservationServiceMock},
        {provide: EquipmentService, useValue: equipmentServiceMock},
        {provide: CustomerProfileService, useValue: customerProfileServiceMock},
        {provide: Router, useValue: routerMock},
        {provide: ActivatedRoute, useValue: activatedRouteMock},
        {provide: ToastrService, useValue: toastrServiceMock}
      ]
    }).compileComponents();

    fixture = TestBed.createComponent(ReservationCreateEditComponent);
    component = fixture.componentInstance;
  });

  it('should create the component', () => {
    fixture.detectChanges();
    expect(component).toBeTruthy();
  });

  it('should load customer profiles on init and patch the first profile ID in create mode', () => {
    fixture.detectChanges();
    expect(customerProfileServiceMock.getCustomerProfiles).toHaveBeenCalledWith();
    expect(component.customerProfiles).toEqual(mockProfiles);
    expect(component.reservationForm.get('customerProfileId')?.value).toBe(1);
  });

  it('should invalid date range if endDate is before startDate', () => {
    fixture.detectChanges();
    component.reservationForm.patchValue({
      startDate: '2026-06-10',
      endDate: '2026-06-05'
    });

    expect(component.isDateRangeInvalid).toBeTrue();
  });

  it('should apply profile filters automatically when profile changes', () => {
    fixture.detectChanges();
    component.currentActiveType = EquipmentType.SKI;

    component.reservationForm.patchValue({customerProfileId: 1});

    expect(component.skillFilter).toBe(SkillLevel.BEGINNER);
    expect(equipmentServiceMock.search).toHaveBeenCalled();
  });

  it('should not submit reservation if form is invalid or no equipment selected', () => {
    fixture.detectChanges();
    component.submitReservation();
    expect(reservationServiceMock.create).not.toHaveBeenCalled();

    component.reservationForm.patchValue({
      customerProfileId: 1,
      pickUpTime: '09:00',
      startDate: '2026-06-01',
      endDate: '2026-06-05'
    });
    component.selectedEquipment = [];

    component.submitReservation();
    expect(toastrServiceMock.warning).toHaveBeenCalledWith('Please choose at least 1 piece of equipment');
    expect(reservationServiceMock.create).not.toHaveBeenCalled();
  });

  it('should successfully submit reservation when confirmed in create mode and show success notification', () => {
    fixture.detectChanges();
    component.reservationForm.patchValue({
      customerProfileId: 1,
      pickUpTime: '09:00',
      startDate: '2026-06-01',
      endDate: '2026-06-05'
    });
    component.selectedEquipment = [...mockEquipment];

    const translateService = TestBed.inject(TranslateService);
    spyOn(translateService, 'instant').and.returnValue('Reservation created');

    component.confirmAndSubmit(mockDialog);

    expect(mockDialog.close).toHaveBeenCalled();
    expect(reservationServiceMock.create).toHaveBeenCalled();
    expect(routerMock.navigate).toHaveBeenCalledWith(['/customer/reservation']);
    expect(toastrServiceMock.success).toHaveBeenCalledWith('Reservation created');
  });

  it('should switch to edit mode and load existing reservation data on init', () => {
    activatedRouteMock.snapshot.data = {mode: ReservationCreateEditMode.edit};
    activatedRouteMock.snapshot.paramMap = convertToParamMap({id: '100'});

    fixture.detectChanges();

    expect(component.mode).toBe(ReservationCreateEditMode.edit);
    expect(component.reservationId).toBe(100);
    expect(reservationServiceMock.getById).toHaveBeenCalledWith(100);

    expect(component.reservationForm.get('customerProfileId')?.value).toBe(1);
    expect(component.reservationForm.get('startDate')?.value).toBe('2026-06-20');
    expect(component.reservationForm.get('pickUpTime')?.value).toBe('10:00');
    expect(component.selectedEquipment).toEqual([mockEquipment[0]]);
  });

  it('should successfully update reservation when confirmed in edit mode', () => {
    activatedRouteMock.snapshot.data = {mode: ReservationCreateEditMode.edit};
    activatedRouteMock.snapshot.paramMap = convertToParamMap({id: '100'});

    fixture.detectChanges();

    component.reservationForm.patchValue({
      customerProfileId: 1,
      pickUpTime: '10:00',
      startDate: '2026-06-20',
      endDate: '2026-06-22'
    });
    component.selectedEquipment = [mockEquipment[0]];

    const translateService = TestBed.inject(TranslateService);
    spyOn(translateService, 'instant').and.returnValue('Reservation updated');

    component.confirmAndSubmit(mockDialog);

    expect(mockDialog.close).toHaveBeenCalled();
    expect(reservationServiceMock.update).toHaveBeenCalledWith(100, {
      id: 100,
      customerProfileId: 1,
      equipmentIds: [10],
      pickUpTime: '10:00:00',
      startDate: '2026-06-20',
      endDate: '2026-06-22'
    });
    expect(routerMock.navigate).toHaveBeenCalledWith(['/customer/reservation']);
    expect(toastrServiceMock.success).toHaveBeenCalledWith('Reservation updated');
  });

  describe('Live Price Calculation', () => {
    beforeEach(() => {
      fixture.detectChanges();
    });

    it('should return 0 if no equipment is selected', () => {
      component.selectedEquipment = [];
      component.reservationForm.patchValue({
        startDate: '2026-06-20',
        endDate: '2026-06-22'
      });

      expect(component.currentTotalPrice).toBe(0);
    });

    it('should return 0 if startDate or endDate is missing', () => {
      component.selectedEquipment = [mockEquipment[0]]; // 25 €

      component.reservationForm.patchValue({startDate: null, endDate: '2026-06-22'});
      expect(component.currentTotalPrice).toBe(0);

      component.reservationForm.patchValue({startDate: '2026-06-20', endDate: null});
      expect(component.currentTotalPrice).toBe(0);
    });

    it('should return 0 if the date range is invalid (end date before start date)', () => {
      component.selectedEquipment = [mockEquipment[0]];
      component.reservationForm.patchValue({
        startDate: '2026-06-20',
        endDate: '2026-06-19'
      });

      expect(component.currentTotalPrice).toBe(0);
    });

    it('should calculate the correct price for a single day rental (same start and end date)', () => {
      component.selectedEquipment = [mockEquipment[0]];
      component.reservationForm.patchValue({
        startDate: '2026-06-20',
        endDate: '2026-06-20'
      });

      expect(component.currentTotalPrice).toBe(25);
    });

    it('should calculate the correct cumulative price for multiple items over multiple days', () => {
      component.selectedEquipment = [mockEquipment[0], mockEquipment[1]];

      component.reservationForm.patchValue({
        startDate: '2026-06-20',
        endDate: '2026-06-22'
      });

      expect(component.currentTotalPrice).toBe(180);
    });
  });
});
