//AI-assisted: Code generated by Google Gemini and adapted to fit project
import { ComponentFixture, TestBed, fakeAsync, tick } from '@angular/core/testing';
import { ReactiveFormsModule, FormBuilder, FormsModule } from '@angular/forms';
import { ActivatedRoute, convertToParamMap, Router } from '@angular/router';
import { of, throwError } from 'rxjs';
import { ReservationCreateEditComponent, ReservationCreateEditMode } from './reservation-create-edit.component';
import { ReservationService } from '../../../../services/reservation.service';
import { EquipmentService } from '../../../../services/equipment.service';
import { CustomerProfileService } from '../../../../services/customer-profile.service';
import { EquipmentType } from '../../../../dtos/equipmenttype';
import { RentalStatus } from '../../../../dtos/rentalstatus';
import { SkillLevel } from '../../../../dtos/skilllevel';
import { TranslateModule } from '@ngx-translate/core';

describe('ReservationCreateEditComponent', () => {
  let component: ReservationCreateEditComponent;
  let fixture: ComponentFixture<ReservationCreateEditComponent>;

  let reservationServiceMock: any;
  let equipmentServiceMock: any;
  let customerProfileServiceMock: any;
  let routerMock: any;
  let activatedRouteMock: any;

  const mockProfiles = [
    { id: 1, profileName: 'Test Profil 1', skillLevel: SkillLevel.BEGINNER, customerId: 1, height: 180, shoeSize: 42, weight: 75 }
  ];

  const mockEquipment = [
    { id: 10, model: 'Ski Alpha', price: 25, equipmentType: EquipmentType.SKI, status: RentalStatus.FREE, targetSkillLevel: SkillLevel.BEGINNER, barcodeId: 'BC-12345' },
    { id: 20, model: 'Ski Beta', price: 35, equipmentType: EquipmentType.SKI, status: RentalStatus.FREE, targetSkillLevel: SkillLevel.ADVANCED, barcodeId: 'BC-54321' }
  ];

  beforeEach(async () => {
    reservationServiceMock = {
      create: jasmine.createSpy('create').and.returnValue(of({ id: 99 })),
      update: jasmine.createSpy('update').and.returnValue(of({ id: 100 })),
      getById: jasmine.createSpy('getById').and.returnValue(of({
        id: 100,
        customerProfileId: 1,
        pickUpDate: '2026-06-20',
        pickUpTime: '10:00',
        rentDurationDays: 3,
        items: [mockEquipment[0]]
      }))
    };

    equipmentServiceMock = {
      search: jasmine.createSpy('search').and.returnValue(of(mockEquipment))
    };

    customerProfileServiceMock = {
      getCustomerProfiles: jasmine.createSpy('getCustomerProfiles').and.returnValue(of(mockProfiles))
    };

    routerMock = {
      navigate: jasmine.createSpy('navigate')
    };

    activatedRouteMock = {
      snapshot: {
        data: { mode: ReservationCreateEditMode.create },
        paramMap: convertToParamMap({})
      }
    };

    await TestBed.configureTestingModule({
      declarations: [
        ReservationCreateEditComponent,
      ],
      imports: [
        ReactiveFormsModule,
        FormsModule,
        TranslateModule.forRoot()
      ],
      providers: [
        FormBuilder,
        { provide: ReservationService, useValue: reservationServiceMock },
        { provide: EquipmentService, useValue: equipmentServiceMock },
        { provide: CustomerProfileService, useValue: customerProfileServiceMock },
        { provide: Router, useValue: routerMock },
        { provide: ActivatedRoute, useValue: activatedRouteMock }
      ]
    }).compileComponents();

    fixture = TestBed.createComponent(ReservationCreateEditComponent);
    component = fixture.componentInstance;

    spyOn(window, 'alert');
  });

  it('should create the component', () => {
    fixture.detectChanges();
    expect(component).toBeTruthy();
  });

  it('should load customer profiles on init and patch the first profile ID in create mode', () => {
    fixture.detectChanges();
    expect(customerProfileServiceMock.getCustomerProfiles).toHaveBeenCalledWith(1);
    expect(component.customerProfiles).toEqual(mockProfiles);
    expect(component.reservationForm.get('customerProfileId')?.value).toBe(1);
  });

  it('should invalid date range if returnDate is before pickUpDate', () => {
    fixture.detectChanges();
    component.reservationForm.patchValue({
      pickUpDate: '2026-06-10',
      returnDate: '2026-06-05'
    });

    expect(component.isDateRangeInvalid).toBeTrue();
    expect(component.calculateRentDuration()).toBe(0);
  });

  it('should calculate correct rent duration for valid dates', () => {
    fixture.detectChanges();
    component.reservationForm.patchValue({
      pickUpDate: '2026-06-01',
      returnDate: '2026-06-05'
    });

    expect(component.isDateRangeInvalid).toBeFalse();
    expect(component.calculateRentDuration()).toBe(5);
  });

  it('should apply profile filters automatically when profile changes', () => {
    fixture.detectChanges();
    component.currentActiveType = EquipmentType.SKI;

    component.reservationForm.patchValue({ customerProfileId: 1 });

    expect(component.skillFilter).toBe(SkillLevel.BEGINNER);
    expect(equipmentServiceMock.search).toHaveBeenCalled();
  });

  it('should not submit reservation if form is invalid or no equipment selected', () => {
    fixture.detectChanges();
    component.submitReservation();
    expect(reservationServiceMock.create).not.toHaveBeenCalled();

    component.reservationForm.patchValue({
      customerProfileId: 1,
      pickUpDate: '2026-06-01',
      pickUpTime: '09:00',
      returnDate: '2026-06-05'
    });
    component.selectedEquipment = [];

    component.submitReservation();
    expect(window.alert).toHaveBeenCalledWith('Please choose at least 1 piece of equipment');
    expect(reservationServiceMock.create).not.toHaveBeenCalled();
  });

  it('should successfully submit reservation when confirmed in create mode', () => {
    fixture.detectChanges();
    component.reservationForm.patchValue({
      customerProfileId: 1,
      pickUpDate: '2026-06-01',
      pickUpTime: '09:00',
      returnDate: '2026-06-05'
    });
    component.selectedEquipment = [...mockEquipment];

    spyOn(window, 'confirm').and.returnValue(true);

    component.submitReservation();

    expect(reservationServiceMock.create).toHaveBeenCalled();
    expect(routerMock.navigate).toHaveBeenCalledWith(['/customer/reservation']);
  });

  it('should trigger equipment validation after date change and remove unavailable equipment', fakeAsync(() => {
    fixture.detectChanges();

    component.selectedEquipment = [{ ...mockEquipment[0] }];

    equipmentServiceMock.search.and.returnValue(of([mockEquipment[1]]));

    component.reservationForm.patchValue({
      pickUpDate: '2026-07-01',
      returnDate: '2026-07-05'
    });

    tick(300);

    expect(component.selectedEquipment.length).toBe(0);
    expect(component.validationWarning).toBe('RESERVATION.VALIDATION_WARNING');
  }));

  it('should switch to edit mode and load existing reservation data on init', () => {
    activatedRouteMock.snapshot.data = { mode: ReservationCreateEditMode.edit };
    activatedRouteMock.snapshot.paramMap = convertToParamMap({ id: '100' });

    fixture.detectChanges();

    expect(component.mode).toBe(ReservationCreateEditMode.edit);
    expect(component.reservationId).toBe(100);
    expect(reservationServiceMock.getById).toHaveBeenCalledWith(100);

    expect(component.reservationForm.get('customerProfileId')?.value).toBe(1);
    expect(component.reservationForm.get('pickUpDate')?.value).toBe('2026-06-20');
    expect(component.reservationForm.get('pickUpTime')?.value).toBe('10:00');
    expect(component.selectedEquipment).toEqual([mockEquipment[0]]);
  });

  it('should successfully update reservation when confirmed in edit mode', () => {
    activatedRouteMock.snapshot.data = { mode: ReservationCreateEditMode.edit };
    activatedRouteMock.snapshot.paramMap = convertToParamMap({ id: '100' });

    fixture.detectChanges();

    component.reservationForm.patchValue({
      customerProfileId: 1,
      pickUpDate: '2026-06-20',
      pickUpTime: '10:00',
      returnDate: '2026-06-22'
    });
    component.selectedEquipment = [mockEquipment[0]];

    spyOn(window, 'confirm').and.returnValue(true);

    component.submitReservation();

    expect(reservationServiceMock.update).toHaveBeenCalledWith(100, {
      id: 100,
      customerProfileId: 1,
      equipmentIds: [10],
      pickUpTime: '10:00:00',
      pickUpDate: '2026-06-20',
      rentDurationDays: 3
    });
    expect(routerMock.navigate).toHaveBeenCalledWith(['/customer/reservation']);
  });
});
