// AI-assisted: Code partially generated by Google Gemini

import {TestBed} from '@angular/core/testing';
import {HttpTestingController, provideHttpClientTesting} from '@angular/common/http/testing';
import {provideHttpClient} from '@angular/common/http';
import {Globals} from '../global/globals';
import {CustomerProfileService} from './customer-profile.service';
import {CustomerProfile} from '../dtos/customer-profile';
import {CustomerProfileCreationUpdate} from '../dtos/customer-profile-creation-update';

describe('CustomerProfileService', () => {
  let service: CustomerProfileService;
  let httpMock: HttpTestingController;
  let globals: Globals;

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [
        CustomerProfileService,
        Globals,
        provideHttpClient(),
        provideHttpClientTesting()
      ]
    });

    service = TestBed.inject(CustomerProfileService);
    httpMock = TestBed.inject(HttpTestingController);
    globals = TestBed.inject(Globals);
  });

  afterEach(() => {
    httpMock.verify();
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  describe('getCustomerProfiles', () => {
    it('should execute a GET request to the correct URL', () => {
      const mockProfiles: CustomerProfile[] = [
        {id: 1} as CustomerProfile,
        {id: 2} as CustomerProfile
      ];

      service.getCustomerProfiles().subscribe((profiles) => {
        expect(profiles).toEqual(mockProfiles);
        expect(profiles.length).toBe(2);
      });

      const req = httpMock.expectOne(`${globals.backendUri}/customers/profiles`);
      expect(req.request.method).toBe('GET');
      req.flush(mockProfiles);
    });
  });

  describe('getProfilesByCustomerId', () => {
    it('should execute a GET request to the correct URL with the customer ID', () => {
      const mockProfiles: CustomerProfile[] = [
        { id: 10 } as CustomerProfile,
        { id: 11 } as CustomerProfile
      ];
      const targetCustomerId = 42;

      service.getCustomerProfilesByCustomerId(targetCustomerId).subscribe((profiles) => {
        expect(profiles).toEqual(mockProfiles);
        expect(profiles.length).toBe(2);
      });

      const req = httpMock.expectOne(`${globals.backendUri}/customers/${targetCustomerId}/profiles`);

      expect(req.request.method).toBe('GET');
      req.flush(mockProfiles);
    });
  });

  describe('getById', () => {
    it('should execute a GET request to fetch a specific profile', () => {
      const profileId = 1;
      const mockProfile: CustomerProfile = {id: profileId} as CustomerProfile;

      service.getById(profileId).subscribe((profile) => {
        expect(profile).toEqual(mockProfile);
      });

      const req = httpMock.expectOne(`${globals.backendUri}/customers/profiles/${profileId}`);
      expect(req.request.method).toBe('GET');
      req.flush(mockProfile);
    });
  });

  describe('delete', () => {
    it('should execute a DELETE request to remove a profile', () => {
      const profileId = 1;

      service.delete(profileId).subscribe(() => {
        expect().nothing();
      });

      const req = httpMock.expectOne(`${globals.backendUri}/customers/profiles/${profileId}`);
      expect(req.request.method).toBe('DELETE');
      req.flush(null);
    });
  });

  describe('create', () => {
    it('should execute a POST request with the correct payload', () => {
      const newProfile: CustomerProfileCreationUpdate = {} as CustomerProfileCreationUpdate;
      const createdProfile: CustomerProfile = {id: 1} as CustomerProfile;

      service.create(newProfile).subscribe((profile) => {
        expect(profile).toEqual(createdProfile);
      });

      const req = httpMock.expectOne(`${globals.backendUri}/customers/profiles`);
      expect(req.request.method).toBe('POST');
      expect(req.request.body).toEqual(newProfile);
      req.flush(createdProfile);
    });
  });

  describe('update', () => {
    it('should execute a PATCH request with the correct payload', () => {
      const profileId = 1;
      const updateData: CustomerProfileCreationUpdate = {} as CustomerProfileCreationUpdate;
      const updatedProfile: CustomerProfile = {id: profileId} as CustomerProfile;

      service.update(profileId, updateData).subscribe((profile) => {
        expect(profile).toEqual(updatedProfile);
      });

      const req = httpMock.expectOne(`${globals.backendUri}/customers/profiles/${profileId}`);
      expect(req.request.method).toBe('PATCH');
      expect(req.request.body).toEqual(updateData);
      req.flush(updatedProfile);
    });
  });

  describe('Error Handling (Negative Tests)', () => {
    it('should throw an error when getById fails with a 404', () => {
      const profileId = 999;
      const mockErrorResponse = {message: 'Profile not found'};

      service.getById(profileId).subscribe({
        next: () => fail('The request should have failed with a 404 error'),
        error: (error) => {
          expect(error.status).toBe(404);
          expect(error.statusText).toBe('Not Found');
        }
      });

      const req = httpMock.expectOne(`${globals.backendUri}/customers/profiles/${profileId}`);

      req.flush(mockErrorResponse, {status: 404, statusText: 'Not Found'});
    });

    it('should throw an error when create fails with a 400 Bad Request', () => {
      const invalidProfile = {} as CustomerProfileCreationUpdate;

      service.create(invalidProfile).subscribe({
        next: () => fail('The request should have failed due to invalid data'),
        error: (error) => {
          expect(error.status).toBe(400);
        }
      });

      const req = httpMock.expectOne(`${globals.backendUri}/customers/profiles`);
      req.flush('Invalid data', {status: 400, statusText: 'Bad Request'});
    });
  });

});
